percona/percona-everest-cli

pkg/kubernetes/client/monitoring.go
EVEREST-281
We failed to discover resource type if monitoring was not enabled
=> EVEREST-281: fix delete cluster fail

cli-tests/tests/help.spec.ts, commands/root.go
EVEREST-292
Rename `everest` to `everestctl`
=> EVEREST-292: fix cli name

pkg/install/operators.go
EVEREST-173
In order to calculate the available disk size in the cluster we require permissions to list PVs.
=> EVEREST-173 add permissions for listing PVs

pkg/install/operators.go
EVEREST-320
This makes communication with Everest synchronous. Moved connecting backups to the last call because it will fail monitoring provisioning
=> EVEREST-320 Make communication with everest synchronous

pkg/logger/logger.go
It removes stacktraces when zap logs an error
=> EVEREST-307 Use ProductionEncoderConfig

install.sh
EVEREST-294
Use docker compose v2 to avoid compatibility issues. See EVEREST-294 for more details on why this is an issue.
=> EVEREST-294 use docker compose v2

commands/delete/cluster.go, commands/install/operators.go, install.sh
EVEREST-319
The order of precedence is the following:
1. --kubeconfig (-k) flag
2. KUBECONFIG env var
3. "~/.kube/config"
=> EVEREST-319 Use KUBECONFIG env var if set

commands/delete.go, commands/root.go
=> EVEREST-420: disable provision command

cli-tests/tests/flow/validation.spec.ts, pkg/install/operators.go
=> EVEREST-386: backup name is required

pkg/kubernetes/kubernetes.go
5-minute timeout should be enough to create an install plan on slow Kubernetes clusters or on clusters with high latency. We had this timeout in PMM/DBaaS for a while and all operators were installed successfully. I tested it on clean GKE deployment using Danil's laptop and it ran successfully. 
The original stacktrace shows that it failed because 2.5 minutes were not enough to create an install plan for the Postgres operator and it gets created a couple of moments later
=> EVEREST-406 Increased timeout for installing operators

commands/install/operators.go, data/crds/olm/percona-dbaas-catalog.yaml
---
**Problem:**
EVEREST-449
*Short explanation of the problem.*
**Related pull requests**
- [link]
**Cause:**
*Short explanation of the root cause of the issue if applicable.*
**Solution:**
*Short explanation of the solution we are providing with this PR.*
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-449 Set monitoring to false by default

pkg/version/version.go, pkg/version/version_test.go
---
**Problem:**
EVEREST-488
*Short explanation of the problem.*
the CLI sets image something like this
```
image: docker.io/percona/everest-catalog:0.3.0-37-gf1f07f6
```
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-488 Fixed catalog versioning

pkg/kubernetes/kubernetes.go
---
**Problem:**
EVEREST-458
*Short explanation of the problem.*
One minute is not enough to wait for the pod to be running 
**Cause:**
*Short explanation of the root cause of the issue if applicable.*
**Solution:**
*Short explanation of the solution we are providing with this PR.*
Increased timeout to 5 minutes
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-458 Increase timeout for restarting pod

.github/workflows/ci.yml, .github/workflows/cli-tests.yml
**Fix integration tests failure**
---
**Problem:**
EVEREST-107
The integration tests were [failing](https://github.com/percona/percona-everest-cli/actions/runs/6589667490/job/17904624216) with
```
2023-10-20T15:27:22Z	error	install/operators.go:207	Could not connect to Everest. Make sure Everest is running and is accessible from this machine.	{"component": "install/operators"}
```
Long story short - BE runs in background too slow and tests are running before it gets available
-------------------
Investigation:
1. Tried to move the BE run to the foreground to check if it gets available it all - [it does](https://github.com/percona/percona-everest-cli/actions/runs/6599336542/job/17928247232).
2. Noticed it takes long to run the BE (perhaps because of the vault has been added)
3. Added the …
=> EVEREST-107 Fix tests run

pkg/install/operators.go
---
**Problem:**
EVEREST-579
**Cause:**
- Everest operator was restart during every provisioning
- It's not required on the first deploy
**Solution:**
- No restart on first deploy
- This does not fix the root cause but shall prevent the issue from occurring during the initial provisioning
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-579: don't restart everest operator

install.sh
**EVEREST-107 remove jq dependency**
---
**Problem:**
EVEREST-107
We have a jq dependency but we don't do any heavy json manipulation.
**Solution:**
Use grep and sed to accomplish the same result.
**CHECKLIST**
---
**Jira**
**Tests**
- ~[ ] Is an Integration test/test case added for the new feature/change?~
- ~[ ] Are unit tests added where appropriate?~
=> EVEREST-107 remove jq dependency

pkg/everest/client/client.go, pkg/kubernetes/kubernetes.go
---
**Problem:**
EVEREST-107
*Short explanation of the problem.*
We can't use the Authorization header because it's automatically removed by the k8s proxy.
**Cause:**
Authorization header is removed by k8s.
**Solution:**
Use cookie
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-107: use cookie instead of auth header

cli-tests/tests/flow/all-operators.spec.ts, cli-tests/tests/flow/mongodb-operator.spec.ts, cli-tests/tests/flow/pg-operator.spec.ts, cli-tests/tests/flow/pxc-operator.spec.ts, install.sh, pkg/install/install.go
**Rename restricted namespaces**
---
**Problem:**
EVEREST-633
`everest-system` and `everest-monitoring` are more descriptive names that `percona-everest` and `percona-everest-monitoring`.
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-633 Rename restricted namespaces

pkg/install/install.go, pkg/kubernetes/client/client.go, pkg/kubernetes/client/kubeclient_interface.go, pkg/kubernetes/client/mock_kube_client_connector.go, pkg/kubernetes/kubernetes.go, pkg/kubernetes/kubernetes_test.go, pkg/kubernetes/olm_operator_test.go
**Fix adding namespaces after initial install**
---
**Problem:**
EVEREST-633
With the initial implementation we weren't able to add new namespaces after initial install.
**Cause:**
The operator subscription was never update which lead to the DB_NAMESPACES env var not change so the everest-operator and everest BE wouldn't know about the new namespces.
**Solution:**
Update the subscription with a merged env var list.
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-633 Fix adding namespaces after initial install

cli-tests/Makefile, cli-tests/tests/flow/all-operators.spec.ts, cli-tests/tests/flow/mongodb-operator.spec.ts, cli-tests/tests/flow/pg-operator.spec.ts, cli-tests/tests/flow/pxc-operator.spec.ts, commands/install.go, commands/upgrade.go, go.mod, go.sum, install.sh, pkg/install/install.go, pkg/kubernetes/kubernetes.go, pkg/upgrade/upgrade.go
**Change the namespace flag**
---
**Problem:**
EVEREST-843
Change `namespace` flag to `namespaces` which accepts the comma-separated list of namespaces
**Cause:**
Consistency reasons: the wizard accepts a comma-separated list.
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-843 Comma-separated namespaces flag

pkg/install/install.go
**Fix namespaces validation**
---
**Problem:**
EVEREST-855
Wizard allowed an empty namespace
**Cause:**
Missed cornercase:`strings.Split` applied to an empty string returns a slice of length 1 (with an empty string as the first element), which from the implementation perspective was considered as a defined namespace. 
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-855 Fix namespaces validation

.golangci.yml, commands/install.go, commands/upgrade.go, pkg/install/install.go, pkg/install/install_test.go, pkg/kubernetes/backup_storage.go, pkg/kubernetes/client/client.go, pkg/uninstall/uninstall.go, pkg/upgrade/upgrade.go
**Namespaces validation improvements**
---
**Problem:**
EVEREST-855
Make validation to cover more corner cases
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-855 Namespaces validation improvements

go.mod, go.sum, pkg/install/install.go, pkg/upgrade/upgrade.go
**Namespaces list fix for wizard**
---
**Problem:**
EVEREST-855
wizard wasn't work right with the new namespaces list 
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-855 Namespaces list fix for wizard

install.sh
Monitoring is always installed so the message in the install.sh script was incorrect
=> EVEREST-107 remove incorrect message in install.sh

cli-tests/playwright.config.ts, cli-tests/tests/flow/all-operators.spec.ts, go.mod, go.sum, pkg/uninstall/uninstall.go
**Workaround waiting for DBs to be deleted**
---
**Problem:**
EVEREST-838
When deleting a DBC CR, the everest operator doesn't wait for the DB operator's CRs to be deleted. Thus, as soon as we delete the DBC CRs, these cease to exist in the cluster and the polling below will return immediately. If we don't wait for the DB operators to process the deletion of the CRs, we may end up deleting the namespaces before the DB operators have a chance to delete the resources they manage, leaving the namespaces in an endless Terminating state waiting for finalizers to be removed.
The everest operator should have a Deleting status that waits for the DB operators to delete their DB CRs before removing the corresponting DBC CR. Until this is implemented, we work around this by sleeping for two minutes …
=> EVEREST-838 Workaround waiting for DBs to be deleted
